#!/bin/sh
set -e

# If the package is removed or installing is aborted, try to remove the
# default mountpoints. Failure to do so is not considered fatal.
if test "$1" = remove || test "$1" = abort-install; then
    rm -f /media/usb 2> /dev/null || :
    for i in 0 1 2 3 4 5 6 7; do
	rmdir /media/usb$i 2> /dev/null || :
    done
fi

# If the package is purged, remove /etc/dev.d/block/usbmount.dev and the
# /etc/udev/rules.d/z60_usbmount.rules symlink if they exist.
if test "$1" = purge; then
    if test -h /etc/udev/rules.d/z60_usbmount.rules; then
	rm -f /etc/udev/rules.d/z60_usbmount.rules
    fi
fi

#DEBHELPER#

exit 0
