#!/bin/sh
set -e

# If the package is removed, try to remove the default mountpoints.
# Failure to do so is not considered fatal.
if test "$1" = remove; then
    rm -f /media/usb 2> /dev/null || :
    for i in 0 1 2 3 4 5 6 7; do
	rmdir /media/usb$i 2> /dev/null || :
    done
fi

# Remove any remaining symlinks in /var/usbmount.
if test "$1" = remove; then
    rm -f /var/usbmount/* 2> /dev/null || :
fi

exit 0
